# deployment manifest to create a pod with 1 replica, change the containers image name as your dockerhub username
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitsearch
  labels:
    app: gitsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitsearch
  template:
    metadata:
      labels:
        app: gitsearch
    spec:
      containers:
        - name: gitsearch
          image: paavithrav07/gitsearch:latest
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 216Mi

# LoadBalancer service to access the application from outside the cluster
---
apiVersion: v1
kind: Service
metadata:
  name: gitsearch
spec:
  type: LoadBalancer
  selector:
    app: gitsearch
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80